"""add_account_money_extend

Revision ID: 005_account_money_extend
Revises: 004_ai_billing_forwarding
Create Date: 2024-07-31 09:35:34.164412

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

from models import db, types

# revision identifiers, used by Alembic.
revision = '005_account_money_extend'
down_revision = '004_ai_billing_forwarding'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    if 'account_money_extend' not in tables:
        op.create_table('account_money_extend',
                        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                        sa.Column('account_id', types.StringUUID(), nullable=False),
                        sa.Column('total_quota', sa.Numeric(precision=16, scale=7), nullable=True),
                        sa.Column('used_quota', sa.Numeric(precision=16, scale=7), nullable=True),
                        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                        sa.PrimaryKeyConstraint('id', name='account_money_pkey')
                        )
        with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
            batch_op.create_index('idx_account_money_account_id', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_account_money_account_id')

    op.drop_table('account_money_extend')
    # ### end Alembic commands ###
