"""add_account_layover_record_extend

Revision ID: 008_account_layover_record
Revises: 007_account_money_monthly_stat
Create Date: 2024-08-27 03:08:09.118504

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

from models import db, types

# revision identifiers, used by Alembic.
revision = '008_account_layover_record'
down_revision = '007_account_money_monthly_stat'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    if 'account_layover_record_extend' not in tables:
        op.create_table('account_layover_record_extend',
        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('account_id', types.StringUUID(), nullable=False),
        sa.Column('forwarding_id', types.StringUUID(), nullable=False),
        sa.Column('money', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='account_layover_record_extend_pkey')
        )
        with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
            batch_op.create_index('idx_account_layover_record_account_id', ['account_id'], unique=False)
            batch_op.create_index('idx_account_layover_record_forwarding_id', ['forwarding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_account_layover_record_forwarding_id')
        batch_op.drop_index('idx_account_layover_record_account_id')

    op.drop_table('account_layover_record_extend')
    # ### end Alembic commands ###
