"""add_api_token_money_extend

Revision ID: 009_api_token_money_extend
Revises: 008_account_layover_record
Create Date: 2024-08-29 07:15:02.913278

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

from models import db, types

# revision identifiers, used by Alembic.
revision = '009_api_token_money_extend'
down_revision = '008_account_layover_record'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    if 'api_token_message_joins_extend' not in tables:
        op.create_table('api_token_message_joins_extend',
        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_token_id', types.StringUUID(), nullable=True),
        sa.Column('record_id', types.StringUUID(), nullable=True),
        sa.Column('app_mode', sa.String(length=255), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='api_token_message_joins_extend_pkey')
        )
        with op.batch_alter_table('api_token_message_joins_extend', schema=None) as batch_op:
            batch_op.create_index('api_token_message_joins_extend_app_token_id_idx', ['app_token_id'], unique=False)
            batch_op.create_index('api_token_message_joins_extend_record_id_idx', ['record_id'], unique=False)

    if 'api_token_money_daily_stat_extend' not in tables:
        op.create_table('api_token_money_daily_stat_extend',
        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_token_id', types.StringUUID(), nullable=False),
        sa.Column('accumulated_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('day_used_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('day_limit_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('stat_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='api_token_money_daily_stat_pkey')
        )
        with op.batch_alter_table('api_token_money_daily_stat_extend', schema=None) as batch_op:
            batch_op.create_index('idx_api_token_money_daily_stat_app_token_id', ['app_token_id'], unique=False)

    if 'api_token_money_extend' not in tables:
        op.create_table('api_token_money_extend',
        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_token_id', types.StringUUID(), nullable=True),
        sa.Column('accumulated_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('day_used_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('month_used_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('day_limit_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('month_limit_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('description', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id', name='api_token_money_extend_pkey')
        )
        with op.batch_alter_table('api_token_money_extend', schema=None) as batch_op:
            batch_op.create_index('api_tokens_money_app_token_id_idx', ['app_token_id'], unique=False)

    if 'api_token_money_monthly_stat_extend' not in tables:
        op.create_table('api_token_money_monthly_stat_extend',
        sa.Column('id', types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_token_id', types.StringUUID(), nullable=False),
        sa.Column('accumulated_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('month_used_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('month_limit_quota', sa.Numeric(precision=16, scale=7), nullable=True),
        sa.Column('stat_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='api_token_money_monthly_stat_pkey')
        )
        with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
            batch_op.create_index('idx_api_token_money_monthly_stat_app_token_id', ['app_token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_api_token_money_monthly_stat_app_token_id')

    op.drop_table('api_token_money_monthly_stat_extend')
    with op.batch_alter_table('api_token_money_extend', schema=None) as batch_op:
        batch_op.drop_index('api_tokens_money_app_token_id_idx')

    op.drop_table('api_token_money_extend')
    with op.batch_alter_table('api_token_money_daily_stat_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_api_token_money_daily_stat_app_token_id')

    op.drop_table('api_token_money_daily_stat_extend')
    with op.batch_alter_table('api_token_message_joins_extend', schema=None) as batch_op:
        batch_op.drop_index('api_token_message_joins_extend_record_id_idx')
        batch_op.drop_index('api_token_message_joins_extend_app_token_id_idx')

    op.drop_table('api_token_message_joins_extend')
    # ### end Alembic commands ###
